// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcN-IWfJr6FNvtjNw8kQ9cdWWBSD6iLYk',
    appId: '1:340853803097:web:cb0d4cd102599c71810948',
    messagingSenderId: '340853803097',
    projectId: 'app-asher-chat',
    authDomain: 'app-asher-chat.firebaseapp.com',
    storageBucket: 'app-asher-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjDXmuaO36VdVUzwCDe_vf9iBMvE6_SpI',
    appId: '1:340853803097:android:b81980efbd5a2e7a810948',
    messagingSenderId: '340853803097',
    projectId: 'app-asher-chat',
    storageBucket: 'app-asher-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCETXm_LceU5hyT4PUnIXOf6ScjajTuWvY',
    appId: '1:340853803097:ios:7d10d8d435289d8c810948',
    messagingSenderId: '340853803097',
    projectId: 'app-asher-chat',
    storageBucket: 'app-asher-chat.firebasestorage.app',
    iosBundleId: 'app.asher.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCETXm_LceU5hyT4PUnIXOf6ScjajTuWvY',
    appId: '1:340853803097:ios:7d10d8d435289d8c810948',
    messagingSenderId: '340853803097',
    projectId: 'app-asher-chat',
    storageBucket: 'app-asher-chat.firebasestorage.app',
    iosBundleId: 'app.asher.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcN-IWfJr6FNvtjNw8kQ9cdWWBSD6iLYk',
    appId: '1:340853803097:web:9efaba012f20005a810948',
    messagingSenderId: '340853803097',
    projectId: 'app-asher-chat',
    authDomain: 'app-asher-chat.firebaseapp.com',
    storageBucket: 'app-asher-chat.firebasestorage.app',
  );
}
